# Generated by Django 4.1.3 on 2022-11-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rights", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
                ("tel", models.CharField(max_length=50)),
                ("tel1", models.CharField(blank=True, max_length=50)),
                ("tel2", models.CharField(blank=True, max_length=50)),
                ("hotline", models.CharField(max_length=50)),
                ("organization", models.CharField(max_length=50)),
                ("funded_by", models.CharField(max_length=50)),
                ("sector", models.CharField(max_length=50)),
                ("service", models.CharField(max_length=50)),
                ("open_hours", models.CharField(max_length=50)),
                ("for_women", models.BooleanField(default=1)),
                ("for_men", models.BooleanField(default=1)),
                ("for_girls", models.BooleanField(default=1)),
                ("for_boys", models.BooleanField(default=1)),
                ("for_seniors", models.BooleanField(default=1)),
                ("for_homeless", models.BooleanField(default=1)),
                ("for_disabled", models.BooleanField(default=1)),
                ("for_lgbt", models.BooleanField(default=1)),
                ("for_refugees", models.BooleanField(default=1)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
