# Generated by Django 4.1.3 on 2022-11-15 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rights", "0003_referral_remote_services"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Referral",
        ),
    ]
