# Generated by Django 4.1.3 on 2022-11-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rights", "0004_delete_referral"),
    ]

    operations = [
        migrations.AlterField(
            model_name="right",
            name="sub_title",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="right",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
