# Generated by Django 4.1.3 on 2023-03-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rights", "0005_alter_right_sub_title_alter_right_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="right",
            name="doc",
            field=models.FileField(blank=True, upload_to="rights/files"),
        ),
    ]
