version: '3.8'

services:
  web:
    build: ./app
    command: bash -c "gunicorn cf.wsgi:application --bind 0.0.0.0:8005 && stripe listen --forward-to 10.10.10.101:8005/support/webhook/"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8005:8005
    env_file:
      - ./.env.prod
    # network_mode: "host"        
    restart: always