# Generated by Django 4.1.3 on 2022-11-13 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SignsAndPrevention",
            new_name="SignAndPrevention",
        ),
        migrations.AlterModelOptions(
            name="signandprevention",
            options={"verbose_name_plural": "signs and prevention"},
        ),
    ]
