# Generated by Django 4.1.3 on 2022-11-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_rename_signsandprevention_signandprevention_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signandprevention",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="typeofabuse",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
