# Generated by Django 4.1.3 on 2022-11-17 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gethelp", "0002_category_referral_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
    ]
