# Generated by Django 4.1.3 on 2022-11-17 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gethelp", "0003_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="category",
            field=models.ForeignKey(
                default=2,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="gethelp.category",
            ),
        ),
    ]
