# Generated by Django 4.1.3 on 2022-11-17 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gethelp", "0004_alter_referral_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="category",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gethelp.category",
            ),
        ),
    ]
