# Generated by Django 4.1.3 on 2022-11-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gethelp", "0005_alter_referral_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("district", models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
