# Generated by Django 4.1.3 on 2022-11-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gethelp", "0007_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="district",
            options={"ordering": ("district",)},
        ),
        migrations.AlterField(
            model_name="location",
            name="location",
            field=models.CharField(max_length=50),
        ),
    ]
