# Generated by Django 4.1.3 on 2022-11-27 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gethelp", "0008_alter_district_options_alter_location_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referral",
            name="address",
        ),
        migrations.RemoveField(
            model_name="referral",
            name="district",
        ),
        migrations.AddField(
            model_name="referral",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gethelp.location",
            ),
        ),
    ]
