# Generated by Django 4.1.3 on 2022-11-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gethelp", "0009_remove_referral_address_remove_referral_district_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ("location",)},
        ),
        migrations.AlterField(
            model_name="category",
            name="category",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="district",
            name="district",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="location",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="referral",
            name="funded_by",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="referral",
            name="hotline",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="referral",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="referral",
            name="open_hours",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="referral",
            name="organization",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="referral",
            name="sector",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="referral",
            name="service",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="referral",
            name="tel",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="referral",
            name="tel1",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="referral",
            name="tel2",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
