# Generated by Django 4.1.3 on 2022-11-27 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gethelp", "0011_alter_location_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ("id",)},
        ),
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("location", "district")},
        ),
    ]
