# Generated by Django 4.1.3 on 2022-11-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gethelp", "0013_alter_location_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="referral",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
