# Generated by Django 4.1.3 on 2022-11-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gethelp", "0014_alter_location_options_alter_referral_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
