# Generated by Django 4.1.3 on 2023-03-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0004_remove_donate_amt_donate_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="donate",
            name="phone",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
