# Generated by Django 4.1.3 on 2023-03-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0010_alter_donate_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="volunteer",
            name="contact",
        ),
        migrations.AddField(
            model_name="volunteer",
            name="email",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="tel",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
