# Generated by Django 4.1.3 on 2023-03-12 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0011_remove_volunteer_contact_volunteer_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="volunteer",
            old_name="tel",
            new_name="phone",
        ),
    ]
