# Generated by Django 4.1.3 on 2023-03-13 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0012_rename_tel_volunteer_phone"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Donate",
            new_name="Donation",
        ),
    ]
