# Generated by Django 4.1.3 on 2023-03-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0014_donation_stripe_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="check_out_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
