# Generated by Django 4.1.3 on 2023-03-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0015_donation_check_out_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("is_subscribed", models.BooleanField(default=True)),
            ],
        ),
    ]
