# Generated by Django 4.1.3 on 2022-11-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="faq",
            old_name="title",
            new_name="question",
        ),
    ]
