# Generated by Django 4.1.3 on 2023-03-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_mythandfact_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="mythandfact",
            name="title",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="whatwedo",
            name="title",
            field=models.TextField(unique=True),
        ),
    ]
